[xdebug]
zend_extension=xdebug.so
xdebug.mode = debug,develop
xdebug.start_with_request = yes
xdebug.client_port = 9003
; Ключевой момент для WSL2/Docker Desktop
xdebug.client_host = host.docker.internal
; Уровень логирования (опционально, для отладки самого Xdebug)
xdebug.log = /var/log/xdebug.log
xdebug.idekey=PHPSTORM
